version: '3'
services:
  rbac-backend:
    image: rbac-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=mysql_rbac  # 明确指定主机名
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=sys
    depends_on:
      mysql_rbac:
        condition: service_healthy  # 等待MySQL健康

  mysql_rbac:
    image: mysql:8.0.29
    privileged: true
    user: root
    # command: --default-authentication-plugin=mysql_native_pas
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sys
    volumes:
      - ./mysqlData:/var/lib/mysql
      - ./doc/sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    healthcheck:  # 健康检查
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p123456"]
      interval: 5s
      timeout: 10s
      retries: 10

  # 新增前端服务配置
  rbac-frontend:
    # 使用已打好的前端镜像，需替换为你实际的镜像名和标签
    image: rbac-frontend
    ports:
      - "8888:8888"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  # Linux需要这个
    depends_on:
      - rbac-backend  # 前端依赖后端服务
