version: '3'
services:
  rbac-backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=sys
    depends_on:
      - mysql_rbac
  mysql_rbac:
    image: mysql:8.0.29
    privileged: true
    user: root
    # command: --default-authentication-plugin=mysql_native_pas
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sys
    volumes:
      - ./mysqlData:/var/lib/mysql
      - ./doc/sql:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"